```python
"""
===============================================================================
RESQ LIVE
National Disaster Management, Early Warning & Emergency Response Platform
===============================================================================

Decision-support prototype.

IMPORTANT:
Risk values generated by this application are NOT official government
warnings and must be verified against authoritative emergency agencies.
===============================================================================
"""

import io
import json
import urllib.parse
import urllib.request
from datetime import datetime, timedelta

import numpy as np
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import streamlit as st
import streamlit.components.v1 as components
from PIL import Image


# =============================================================================
# PAGE CONFIGURATION
# =============================================================================

st.set_page_config(
    page_title="ResQ Live | Disaster Early Warning & Response",
    page_icon="🛰️",
    layout="wide",
    initial_sidebar_state="expanded",
)


# =============================================================================
# GLOBAL CSS
# =============================================================================

st.markdown(
    """
<style>

html, body, [class*="css"] {
    font-size: 17px !important;
}

.stApp {
    background-color: #f5f8fb;
}

p, li, label, span {
    line-height: 1.5 !important;
}

h1 {
    font-size: 38px !important;
    font-weight: 800 !important;
    color: #063b63 !important;
}

h2 {
    font-size: 30px !important;
    font-weight: 800 !important;
    color: #075985 !important;
}

h3 {
    font-size: 24px !important;
    font-weight: 750 !important;
    color: #174e70 !important;
}

section[data-testid="stSidebar"] {
    background: #eef6fa;
}

section[data-testid="stSidebar"] p,
section[data-testid="stSidebar"] label,
section[data-testid="stSidebar"] span {
    font-size: 16px !important;
}

.stButton > button {
    min-height: 50px !important;
    font-size: 17px !important;
    font-weight: 700 !important;
    border-radius: 10px !important;
}

button[data-baseweb="tab"] {
    font-size: 16px !important;
    font-weight: 700 !important;
}

.resq-header {
    background: linear-gradient(
        135deg,
        #063b63 0%,
        #075985 55%,
        #0e7490 100%
    );
    border-radius: 18px;
    padding: 25px 30px;
    margin-bottom: 18px;
    box-shadow: 0 5px 20px rgba(0,0,0,0.16);
    color: white;
}

.resq-header-title {
    font-size: 31px;
    font-weight: 900;
    color: white;
    line-height: 1.2;
}

.resq-header-subtitle {
    margin-top: 8px;
    font-size: 17px;
    color: #d9f5ff;
}

.risk-card {
    border-radius: 17px;
    padding: 21px;
    min-height: 175px;
    background: white;
    box-shadow: 0 4px 14px rgba(0,0,0,0.08);
    border-left: 7px solid #0e7490;
    margin-bottom: 15px;
}

.risk-card-danger {
    border-left-color: #dc2626;
    background: #fff5f5;
}

.risk-card-warning {
    border-left-color: #f59e0b;
    background: #fffaf0;
}

.risk-card-safe {
    border-left-color: #16a34a;
    background: #f2fff5;
}

.risk-card-title {
    font-size: 21px;
    font-weight: 800;
    margin-bottom: 7px;
}

.risk-card-value {
    font-size: 30px;
    font-weight: 900;
    margin: 7px 0;
}

.risk-card-text {
    font-size: 16px;
    line-height: 1.5;
}

.critical-banner {
    background: linear-gradient(
        90deg,
        #991b1b,
        #dc2626,
        #991b1b
    );
    color: white;
    border-radius: 16px;
    padding: 20px 24px;
    font-size: 21px;
    font-weight: 900;
    text-align: center;
    margin: 15px 0;
    box-shadow: 0 0 25px rgba(220,38,38,0.45);
}

.sos-wrapper {
    background: #fff1f2;
    border: 4px solid #dc2626;
    border-radius: 20px;
    padding: 22px;
    box-shadow: 0 0 25px rgba(220,38,38,0.30);
    margin-bottom: 20px;
}

.sos-title {
    color: #b91c1c;
    font-size: 28px;
    font-weight: 900;
}

.info-panel {
    background: white;
    border-radius: 16px;
    padding: 20px;
    border: 1px solid #dbe7ef;
    box-shadow: 0 3px 10px rgba(0,0,0,0.06);
}

div[data-testid="stMetricValue"] {
    font-size: 32px !important;
    font-weight: 800 !important;
}

div[data-testid="stMetricLabel"] {
    font-size: 16px !important;
    font-weight: 700 !important;
}

</style>
""",
    unsafe_allow_html=True,
)


# =============================================================================
# MONITORED SECTORS
# =============================================================================

MONITORED_SECTORS = {
    "Mumbai & Konkan Coastal Belt (Flood / Cyclone Watch)": {
        "lat": 19.0760,
        "lon": 72.8777,
        "region_code": "WEST_COAST",
        "bbox": "68,14,78,24",
        "river_basin": "Mithi & Ulhas Basin",
        "normal_river_level": 7.20,
    },
    "Brahmaputra Basin - Guwahati / Assam (Severe Flood Watch)": {
        "lat": 26.1445,
        "lon": 91.7362,
        "region_code": "NORTHEAST",
        "bbox": "88,22,98,30",
        "river_basin": "Brahmaputra Upper Reach",
        "normal_river_level": 49.50,
    },
    "Chennai & Coastal Tamil Nadu (Cyclone / Inundation Watch)": {
        "lat": 13.0827,
        "lon": 80.2707,
        "region_code": "SOUTH_EAST",
        "bbox": "77,8,84,16",
        "river_basin": "Adyar & Cooum Basin",
        "normal_river_level": 6.80,
    },
    "Kolkata & Sundarbans Delta (Storm Surge & Tide Watch)": {
        "lat": 22.5726,
        "lon": 88.3639,
        "region_code": "BAY_OF_BENGAL",
        "bbox": "84,18,92,26",
        "river_basin": "Hooghly & Matla Estuary",
        "normal_river_level": 5.40,
    },
    "Puri & Odisha Coastal Corridor (Cyclone Belt)": {
        "lat": 19.8135,
        "lon": 85.8312,
        "region_code": "BAY_OF_BENGAL",
        "bbox": "80,16,89,24",
        "river_basin": "Mahanadi Delta",
        "normal_river_level": 24.10,
    },
    "Kochi & Western Ghats (Kerala Flood / Landslide Watch)": {
        "lat": 9.9312,
        "lon": 76.2673,
        "region_code": "SOUTH_WEST",
        "bbox": "74,7,79,14",
        "river_basin": "Periyar River Basin",
        "normal_river_level": 12.30,
    },
    "Uttarakhand Himalayan Belt (Cloudburst / Landslide Watch)": {
        "lat": 30.3165,
        "lon": 78.0322,
        "region_code": "NORTH_HIMALAYA",
        "bbox": "76,28,82,33",
        "river_basin": "Alaknanda & Bhagirathi",
        "normal_river_level": 340.00,
    },
    "All India & South Asia (National Earth Observation Macro View)": {
        "lat": 20.5937,
        "lon": 78.9629,
        "region_code": "ALL_INDIA",
        "bbox": "65,5,98,37",
        "river_basin": "National Multi-Basin Grid",
        "normal_river_level": 15.00,
    },
}


# =============================================================================
# LIVE WEATHER
# =============================================================================

@st.cache_data(ttl=600, show_spinner=False)
def fetch_live_meteorological_telemetry(lat, lon):

    base_url = "https://api.open-meteo.com/v1/forecast"

    params = {
        "latitude": lat,
        "longitude": lon,
        "current": (
            "temperature_2m,"
            "relative_humidity_2m,"
            "precipitation,"
            "wind_speed_10m,"
            "surface_pressure"
        ),
    }

    url = base_url + "?" + urllib.parse.urlencode(params)

    try:
        req = urllib.request.Request(
            url,
            headers={
                "User-Agent": "ResQ-Live-Disaster-Portal/4.0"
            },
        )

        with urllib.request.urlopen(req, timeout=8) as response:
            data = json.loads(
                response.read().decode("utf-8")
            )

        current = data.get("current", {})

        return {
            "success": True,
            "temperature": float(
                current.get("temperature_2m", 28.5)
            ),
            "humidity": float(
                current.get("relative_humidity_2m", 82)
            ),
            "precipitation": float(
                current.get("precipitation", 0.0)
            ),
            "wind_speed": float(
                current.get("wind_speed_10m", 15.0)
            ),
            "pressure": float(
                current.get("surface_pressure", 1008.0)
            ),
            "timestamp": current.get(
                "time",
                datetime.now().strftime("%Y-%m-%dT%H:%M")
            ),
            "source": "Open-Meteo Live Weather Telemetry",
        }

    except Exception as exc:

        return {
            "success": False,
            "temperature": 29.2,
            "humidity": 84.0,
            "precipitation": 0.0,
            "wind_speed": 20.0,
            "pressure": 1005.0,
            "timestamp": datetime.now().strftime(
                "%Y-%m-%dT%H:%M"
            ),
            "source": "Telemetry Standby / API Unavailable",
            "error": str(exc),
        }


# =============================================================================
# NASA GIBS SATELLITE
# =============================================================================

@st.cache_data(ttl=900, show_spinner=False)
def fetch_nasa_gibs_satellite_image(
    bbox,
    layer="VIIRS_SNPP_CorrectedReflectance_TrueColor",
    target_date=None,
):

    if target_date is None:
        target_date = (
            datetime.utcnow() - timedelta(days=1)
        ).strftime("%Y-%m-%d")

    params = {
        "SERVICE": "WMS",
        "REQUEST": "GetMap",
        "LAYERS": layer,
        "FORMAT": "image/jpeg",
        "HEIGHT": "480",
        "WIDTH": "740",
        "VERSION": "1.1.1",
        "SRS": "EPSG:4326",
        "BBOX": bbox,
        "TIME": target_date,
    }

    base_url = (
        "https://gibs.earthdata.nasa.gov/wms/"
        "epsg4326/best/wms.cgi"
    )

    url = base_url + "?" + urllib.parse.urlencode(params)

    try:

        req = urllib.request.Request(
            url,
            headers={
                "User-Agent": "ResQ-Live-Satellite/4.0"
            },
        )

        with urllib.request.urlopen(req, timeout=10) as response:

            content_type = response.headers.get(
                "Content-Type",
                ""
            )

            if response.status == 200 and "image" in content_type:

                image_data = response.read()

                image = Image.open(
                    io.BytesIO(image_data)
                )

                return (
                    image,
                    url,
                    "NASA Earthdata GIBS",
                )

    except Exception:
        pass

    return (
        None,
        url,
        "NASA GIBS Endpoint",
    )


# =============================================================================
# RAINVIEWER
# =============================================================================

@st.cache_data(ttl=300, show_spinner=False)
def get_rainviewer_radar_tile_path():

    fallback = (
        "https://tilecache.rainviewer.com/"
        "v2/radar/live/256/"
        "{z}/{x}/{y}/2/1_1.png"
    )

    try:

        url = (
            "https://api.rainviewer.com/"
            "public/weather-maps.json"
        )

        req = urllib.request.Request(
            url,
            headers={
                "User-Agent": "ResQ-Live-Radar/4.0"
            },
        )

        with urllib.request.urlopen(req, timeout=7) as response:

            data = json.loads(
                response.read().decode("utf-8")
            )

        host = data.get(
            "host",
            "https://tilecache.rainviewer.com"
        )

        past_radar = (
            data.get("radar", {})
            .get("past", [])
        )

        if past_radar:

            latest_path = past_radar[-1].get("path")

            if latest_path:

                return (
                    f"{host}{latest_path}"
                    "/256/{z}/{x}/{y}/2/1_1.png"
                )

    except Exception:
        pass

    return fallback


# =============================================================================
# SESSION STATE
# =============================================================================

def init_session_state():

    if "initialized" not in st.session_state:

        st.session_state.initialized = True

        st.session_state.selected_sector_name = (
            list(MONITORED_SECTORS.keys())[0]
        )

        st.session_state.current_hazard_status = "ELEVATED"

        st.session_state.topic_bulletins = {
            "Floods & Inundation": {
                "status": "WATCH",
                "severity_score": 78,
                "latest_update": (
                    "Heavy catchment runoff is being monitored "
                    "in the basin. Low-lying settlements should "
                    "remain prepared for rapidly changing water levels."
                ),
                "station_gauge": (
                    "Illustrative gauge: 8.42m | "
                    "Alert reference: 8.00m"
                ),
                "action_status": (
                    "Floodgate and drainage readiness recommended."
                ),
                "issued_by": "Decision-support bulletin",
                "time": "12 mins ago",
            },
            "Cyclones & Storms": {
                "status": "ADVISORY",
                "severity_score": 65,
                "latest_update": (
                    "Strong winds and heavy rainfall are being "
                    "monitored over the selected region."
                ),
                "station_gauge": (
                    "Pressure and wind telemetry under monitoring."
                ),
                "action_status": (
                    "Coastal caution and preparedness recommended."
                ),
                "issued_by": "Decision-support bulletin",
                "time": "28 mins ago",
            },
            "Wildfires & Heat Anomaly": {
                "status": "NORMAL",
                "severity_score": 24,
                "latest_update": (
                    "Thermal anomaly monitoring is active. "
                    "No confirmed major wildfire is represented "
                    "by this prototype."
                ),
                "station_gauge": (
                    "Thermal anomaly index: monitoring mode."
                ),
                "action_status": (
                    "Continue forest and thermal surveillance."
                ),
                "issued_by": "Decision-support bulletin",
                "time": "1 hour ago",
            },
            "Landslides & Mudflows": {
                "status": "WARNING",
                "severity_score": 82,
                "latest_update": (
                    "Slope saturation and prolonged rainfall "
                    "can increase landslide probability in steep "
                    "terrain and road-cut sections."
                ),
                "station_gauge": (
                    "Illustrative infiltration rate: 42 mm/h."
                ),
                "action_status": (
                    "Inspect vulnerable slopes and road corridors."
                ),
                "issued_by": "Decision-support bulletin",
                "time": "4 mins ago",
            },
            "Earthquakes & Seismic": {
                "status": "NORMAL",
                "severity_score": 18,
                "latest_update": (
                    "No confirmed major seismic event is represented "
                    "in this prototype's demonstration dataset."
                ),
                "station_gauge": (
                    "Seismic monitoring connection required for live data."
                ),
                "action_status": (
                    "Maintain continuous seismic monitoring."
                ),
                "issued_by": "Decision-support bulletin",
                "time": "35 mins ago",
            },
        }

        st.session_state.active_early_warnings = [
            {
                "id": "EW-2026-081",
                "hazard": "Riverine Flood & Coastal Surge",
                "region": "Basin Sector & Coastal Inundation Corridor",
                "predicted_severity": "High (Level 3)",
                "est_impact_window": "Next 12–24 Hours",
                "action": (
                    "Prepare flood response resources and "
                    "monitor vulnerable settlements."
                ),
                "timestamp": (
                    datetime.now() - timedelta(hours=2)
                ).strftime("%Y-%m-%d %H:%M"),
            }
        ]

        st.session_state.automated_dispatches = [
            {
                "dispatch_id": "DISP-8901",
                "hazard_trigger": "River Water Level Breach",
                "unit": "NDRF Water Rescue Unit",
                "destination": "Riverbank Zone B",
                "status": "En Route",
                "time_triggered": (
                    datetime.now() - timedelta(minutes=45)
                ).strftime("%H:%M:%S"),
            },
            {
                "dispatch_id": "DISP-8902",
                "hazard_trigger": "Hill Slope Saturation",
                "unit": "SDRF Clearance Unit",
                "destination": "Mountain Highway Pass",
                "status": "On Scene",
                "time_triggered": (
                    datetime.now()
                    - timedelta(hours=1, minutes=10)
                ).strftime("%H:%M:%S"),
            },
        ]

        st.session_state.sos_signals = [
            {
                "sos_id": "SOS-1042",
                "latitude": 19.0760,
                "longitude": 72.8777,
                "triage": "Critical Medical Need",
                "people_count": 4,
                "details": "Demonstration SOS signal.",
                "status": "Assigned",
                "timestamp": (
                    datetime.now() - timedelta(minutes=20)
                ).strftime("%H:%M:%S"),
            }
        ]

        st.session_state.damage_reports = [
            {
                "report_id": "REP-501",
                "location": "Green Valley Block C",
                "damage_type": "Road Blockage & Mudslide",
                "severity": "Severe",
                "casualties": 0,
                "supplies_needed": (
                    "Heavy Earthmovers, Drinking Water"
                ),
                "status": "Under Assessment",
                "timestamp": (
                    datetime.now() - timedelta(days=1)
                ).strftime("%Y-%m-%d %H:%M"),
            }
        ]

        st.session_state.relief_inventory = {
            "Clean Drinking Water Kits (10L)": {
                "requested": 1200,
                "dispatched": 950,
            },
            "Emergency High-Energy Rations": {
                "requested": 2500,
                "dispatched": 2100,
            },
            "Medical Trauma First Aid Kits": {
                "requested": 400,
                "dispatched": 380,
            },
            "Waterproof Family Tarps & Tents": {
                "requested": 850,
                "dispatched": 620,
            },
            "Mobile Diesel Power Generators": {
                "requested": 60,
                "dispatched": 42,
            },
        }


init_session_state()


# =============================================================================
# HEADER
# =============================================================================

col_logo, col_title = st.columns(
    [1.25, 6],
    vertical_alignment="center",
)

with col_logo:

    try:
        st.image(
            "resq_logo.png",
            width=220,
        )

    except Exception:

        st.markdown(
            """
            <div style="
                background:#063b63;
                color:white;
                border-radius:16px;
                padding:25px 15px;
                text-align:center;
                font-weight:900;
                font-size:30px;
            ">
                RESQ<br>
                <span style="
                    color:#43c6c8;
                    font-size:14px;
                ">
                    DISASTER MANAGEMENT
                </span>
            </div>
            """,
            unsafe_allow_html=True,
        )


with col_title:

    st.markdown(
        """
        <div class="resq-header">

            <div class="resq-header-title">
                NATIONAL DISASTER MANAGEMENT
                & EARLY-WARNING PORTAL
            </div>

            <div class="resq-header-subtitle">
                Satellite Intelligence • Drone Reconnaissance •
                AI Risk Analysis • Emergency Response • Recovery
            </div>

        </div>
        """,
        unsafe_allow_html=True,
    )


st.info(
    "🛰️ **RESQ LIVE MONITORING NETWORK:** "
    "Satellite observation + weather telemetry + "
    "risk analytics + emergency response coordination"
)


# =============================================================================
# SIDEBAR
# =============================================================================

try:
    st.sidebar.image(
        "resq_logo.png",
        use_container_width=True,
    )
except Exception:
    st.sidebar.markdown(
        """
        <div style="
            background:#063b63;
            color:white;
            padding:15px;
            border-radius:12px;
            text-align:center;
            font-weight:850;
            font-size:18px;
        ">
            RESQ LIVE<br>
            DISASTER INTELLIGENCE
        </div>
        """,
        unsafe_allow_html=True,
    )


st.sidebar.markdown("---")

st.sidebar.title("📍 Monitoring Sector")

selected_sector = st.sidebar.selectbox(
    "Select monitored area:",
    list(MONITORED_SECTORS.keys()),
    index=0,
)

st.session_state.selected_sector_name = selected_sector

sector_meta = MONITORED_SECTORS[selected_sector]


# =============================================================================
# LIVE WEATHER SIDEBAR
# =============================================================================

live_telemetry = fetch_live_meteorological_telemetry(
    sector_meta["lat"],
    sector_meta["lon"],
)

st.sidebar.markdown("---")
st.sidebar.markdown("### 📡 Live Weather Telemetry")

st.sidebar.write(
    f"**Coordinates:** "
    f"{sector_meta['lat']:.4f}°N, "
    f"{sector_meta['lon']:.4f}°E"
)

st.sidebar.write(
    f"**Temperature:** "
    f"{live_telemetry['temperature']:.1f} °C"
)

st.sidebar.write(
    f"**Humidity:** "
    f"{live_telemetry['humidity']:.0f} %"
)

st.sidebar.write(
    f"**Precipitation:** "
    f"{live_telemetry['precipitation']:.1f} mm"
)

st.sidebar.write(
    f"**Wind:** "
    f"{live_telemetry['wind_speed']:.1f} km/h"
)

st.sidebar.write(
    f"**Pressure:** "
    f"{live_telemetry['pressure']:.1f} hPa"
)

st.sidebar.caption(
    f"Source: {live_telemetry['source']}"
)

if st.sidebar.button(
    "🔄 Sync Live Feeds",
    use_container_width=True,
):

    st.cache_data.clear()
    st.rerun()


# =============================================================================
# OPERATIONAL PHASE
# =============================================================================

st.sidebar.markdown("---")

app_phase = st.sidebar.radio(
    "Operational Phase:",
    [
        "1. BEFORE Disaster",
        "2. DURING Disaster",
        "3. AFTER Disaster",
        "4. System Settings",
    ],
)


# =============================================================================
# EMERGENCY BROADCAST
# =============================================================================

st.sidebar.markdown("---")

if st.sidebar.button(
    "🚨 BROADCAST EMERGENCY WARNING",
    use_container_width=True,
):

    new_alert = {
        "id": (
            f"EW-{datetime.now().strftime('%Y-%m%d-%H%M%S')}"
        ),
        "hazard": "Severe Meteorological Event",
        "region": selected_sector,
        "predicted_severity": "Critical Category",
        "est_impact_window": "Immediate",
        "action": (
            "Activate emergency preparedness procedures "
            "and follow instructions from authorities."
        ),
        "timestamp": datetime.now().strftime(
            "%Y-%m-%d %H:%M"
        ),
    }

    st.session_state.active_early_warnings.insert(
        0,
        new_alert,
    )

    st.session_state.current_hazard_status = "CRITICAL"

    st.sidebar.error(
        "Emergency warning added to console."
    )


# =============================================================================
# BULLETIN TICKER
# =============================================================================

ticker_items = [
    "🌊 **FLOOD MONITOR:** Hydrological conditions are being monitored.",
    "🌪️ **STORM MONITOR:** Wind, pressure and rainfall conditions are being monitored.",
    "🏔️ **LANDSLIDE MONITOR:** Slope saturation and rainfall conditions are being monitored.",
]

st.warning("  |  ".join(ticker_items))


# =============================================================================
# BEFORE DISASTER
# =============================================================================

if app_phase == "1. BEFORE Disaster":

    st.title(
        "🛡️ BEFORE DISASTER — Prediction & Early Warning"
    )

    st.markdown(
        """
        **Mission:** Understand the current condition of the selected
        area, identify potential hazards, estimate where risk may
        increase, and prepare response teams before conditions become critical.
        """
    )

    # -------------------------------------------------------------------------
    # LIVE CONDITIONS
    # -------------------------------------------------------------------------

    st.markdown("## 📍 Current Area Situation")

    rainfall_12h = float(
        live_telemetry["precipitation"] * 12
    )

    wind_current = float(
        live_telemetry["wind_speed"]
    )

    humidity_current = float(
        live_telemetry["humidity"]
    )

    temperature_current = float(
        live_telemetry["temperature"]
    )

    pressure_current = float(
        live_telemetry["pressure"]
    )

    # -------------------------------------------------------------------------
    # RISK CALCULATIONS
    # -------------------------------------------------------------------------

    flood_risk = min(
        100,
        max(
            0,
            int(
                rainfall_12h * 0.30
                + humidity_current * 0.20
                + wind_current * 0.10
            ),
        ),
    )

    landslide_risk = min(
        100,
        max(
            0,
            int(
                rainfall_12h * 0.35
                + humidity_current * 0.30
            ),
        ),
    )

    wildfire_risk = min(
        100,
        max(
            0,
            int(
                temperature_current * 1.5
                + wind_current * 0.30
                - humidity_current * 0.55
                - rainfall_12h * 0.25
            ),
        ),
    )

    cyclone_risk = min(
        100,
        max(
            0,
            int(
                wind_current * 0.45
                + rainfall_12h * 0.20
            ),
        ),
    )

    risk_dictionary = {
        "Flood / Inundation": flood_risk,
        "Landslide / Mudflow": landslide_risk,
        "Wildfire / Heat": wildfire_risk,
        "Cyclone / Severe Storm": cyclone_risk,
    }

    highest_hazard = max(
        risk_dictionary,
        key=risk_dictionary.get,
    )

    highest_score = risk_dictionary[highest_hazard]

    if highest_score >= 75:
        risk_label = "CRITICAL"
        risk_color_class = "risk-card-danger"
    elif highest_score >= 50:
        risk_label = "ELEVATED"
        risk_color_class = "risk-card-warning"
    else:
        risk_label = "LOW / STABLE"
        risk_color_class = "risk-card-safe"

    # -------------------------------------------------------------------------
    # SUMMARY CARD
    # -------------------------------------------------------------------------

    st.markdown(
        f"""
        <div class="risk-card {risk_color_class}">

            <div class="risk-card-title">
                📍 {selected_sector}
            </div>

            <div class="risk-card-value">
                {risk_label} — {highest_score}% Composite Risk
            </div>

            <div class="risk-card-text">

                <b>Primary potential hazard:</b>
                {highest_hazard}

                <br>

                <b>Temperature:</b>
                {temperature_current:.1f} °C

                &nbsp; | &nbsp;

                <b>Humidity:</b>
                {humidity_current:.0f}%

                &nbsp; | &nbsp;

                <b>Wind:</b>
                {wind_current:.1f} km/h

                <br>

                <b>12-hour rainfall estimate:</b>
                {rainfall_12h:.1f} mm

                &nbsp; | &nbsp;

                <b>Pressure:</b>
                {pressure_current:.1f} hPa

            </div>

        </div>
        """,
        unsafe_allow_html=True,
    )

    # -------------------------------------------------------------------------
    # INTELLIGENCE CARDS
    # -------------------------------------------------------------------------

    card1, card2, card3 = st.columns(3)

    with card1:

        st.markdown(
            f"""
            <div class="risk-card">

                <div class="risk-card-title">
                    🛰️ Satellite Intelligence
                </div>

                <div class="risk-card-value">
                    {highest_score}%
                </div>

                <div class="risk-card-text">

                    Satellite observation can monitor:

                    <br><br>

                    • Surface water / inundation<br>
                    • Cloud development<br>
                    • Thermal anomalies<br>
                    • Vegetation stress<br>
                    • Environmental change

                    <br><br>

                    <b>Status:</b>
                    Earth-observation monitoring active

                </div>

            </div>
            """,
            unsafe_allow_html=True,
        )

    with card2:

        st.markdown(
            """
            <div class="risk-card">

                <div class="risk-card-title">
                    🚁 Drone Reconnaissance
                </div>

                <div class="risk-card-value">
                    READY
                </div>

                <div class="risk-card-text">

                    Recommended inspection targets:

                    <br><br>

                    • Flooded roads<br>
                    • Bridges<br>
                    • River embankments<br>
                    • Landslide slopes<br>
                    • Evacuation routes<br>
                    • Cloud-obscured areas

                    <br><br>

                    <b>Feed status:</b>
                    UAV API / ground station required.

                </div>

            </div>
            """,
            unsafe_allow_html=True,
        )

    with card3:

        if highest_score >= 75:
            impact_window = "0–12 HOURS"
        elif highest_score >= 50:
            impact_window = "12–24 HOURS"
        else:
            impact_window = "24–48 HOURS / MONITOR"

        st.markdown(
            f"""
            <div class="risk-card">

                <div class="risk-card-title">
                    ⚠️ Potential Impact Window
                </div>

                <div class="risk-card-value">
                    {impact_window}
                </div>

                <div class="risk-card-text">

                    <b>Potential threat:</b>
                    {highest_hazard}

                    <br><br>

                    This is a
                    <b>model-based decision-support estimate</b>.

                    <br><br>

                    Verify with official warnings and field observations.

                </div>

            </div>
            """,
            unsafe_allow_html=True,
        )

    # -------------------------------------------------------------------------
    # RISK MAP
    # -------------------------------------------------------------------------

    st.markdown("---")
    st.markdown("## 🗺️ Where Could the Disaster Occur?")

    st.info(
        f"""
        **Current model indication:** {highest_hazard} risk estimate
        is **{highest_score}%**.

        The map shows a modeled monitoring zone around the selected
        location. It is not a precise disaster boundary.
        """
    )

    lat_offsets = np.linspace(-0.10, 0.10, 11)
    lon_offsets = np.linspace(-0.10, 0.10, 11)

    impact_points = []

    for lat_offset in lat_offsets:

        for lon_offset in lon_offsets:

            distance = (
                abs(lat_offset) +
                abs(lon_offset)
            )

            local_risk = max(
                0,
                highest_score - int(distance * 160)
            )

            if local_risk >= 75:
                zone = "HIGH PRIORITY"
            elif local_risk >= 50:
                zone = "ELEVATED"
            else:
                zone = "LOWER MONITORING"

            impact_points.append(
                {
                    "Latitude": (
                        sector_meta["lat"] +
                        lat_offset
                    ),
                    "Longitude": (
                        sector_meta["lon"] +
                        lon_offset
                    ),
                    "Risk (%)": local_risk,
                    "Zone": zone,
                }
            )

    impact_df = pd.DataFrame(impact_points)

    try:

        fig_impact = px.scatter_map(
            impact_df,
            lat="Latitude",
            lon="Longitude",
            color="Risk (%)",
            size="Risk (%)",
            hover_data={
                "Latitude": ":.4f",
                "Longitude": ":.4f",
                "Risk (%)": True,
                "Zone": True,
            },
            color_continuous_scale=[
                [0.0, "#16a34a"],
                [0.40, "#84cc16"],
                [0.55, "#f59e0b"],
                [0.75, "#ef4444"],
                [1.0, "#7f1d1d"],
            ],
            zoom=8,
            height=560,
        )

        fig_impact.update_layout(
            map_style="open-street-map",
            margin=dict(
                l=0,
                r=0,
                t=0,
                b=0,
            ),
        )

        st.plotly_chart(
            fig_impact,
            use_container_width=True,
        )

    except Exception:

        st.warning(
            "Interactive map is unavailable in this Plotly version. "
            "Showing a fallback geographic chart."
        )

        fig_fallback = px.scatter(
            impact_df,
            x="Longitude",
            y="Latitude",
            color="Risk (%)",
            size="Risk (%)",
            hover_data=["Zone"],
            color_continuous_scale="RdYlGn_r",
        )

        fig_fallback.update_layout(
            height=500,
            xaxis_title="Longitude",
            yaxis_title="Latitude",
        )

        st.plotly_chart(
            fig_fallback,
            use_container_width=True,
        )

    st.caption(
        "🟢 Lower monitoring priority • "
        "🟠 Elevated • "
        "🔴 High-priority modeled area"
    )

    # -------------------------------------------------------------------------
    # CROSS CHECK
    # -------------------------------------------------------------------------

    st.markdown("## 🛰️🚁 Satellite + Drone Cross-Check")

    cross1, cross2 = st.columns(2)

    with cross1:

        st.markdown(
            f"""
            <div class="info-panel">

                <h3>🛰️ Satellite Intelligence</h3>

                <b>Area:</b> {selected_sector}

                <br><br>

                <b>Monitoring:</b>

                <br>
                • Surface water changes<br>
                • Cloud formations<br>
                • Thermal anomalies<br>
                • Vegetation conditions<br>
                • Environmental changes

                <br><br>

                <b>Satellite layer:</b>
                NASA Earth-observation imagery

            </div>
            """,
            unsafe_allow_html=True,
        )

    with cross2:

        st.markdown(
            """
            <div class="info-panel">

                <h3>🚁 Drone Reconnaissance</h3>

                <b>Recommended mission:</b>

                <br><br>

                1. Inspect roads and bridges<br>
                2. Inspect riverbanks<br>
                3. Search inaccessible areas<br>
                4. Inspect vulnerable slopes<br>
                5. Verify satellite observations<br>
                6. Support evacuation planning

                <br><br>

                <b>Status:</b>
                UAV telemetry connection required

            </div>
            """,
            unsafe_allow_html=True,
        )

    # -------------------------------------------------------------------------
    # TABS
    # -------------------------------------------------------------------------

    (
        tab_satellites,
        tab_predictive,
        tab_bulletins,
        tab_preparedness,
    ) = st.tabs(
        [
            "🛰️ Satellite & Radar",
            "🤖 AI Risk Analytics",
            "📢 Disaster Bulletins",
            "📋 Preparedness & Evacuation",
        ]
    )

    # -------------------------------------------------------------------------
    # SATELLITE TAB
    # -------------------------------------------------------------------------

    with tab_satellites:

        st.subheader(
            "🛰️ Live Earth Observation & Radar"
        )

        sat_layer_choice = st.selectbox(
            "Select observation layer:",
            [
                "NASA VIIRS True Color",
                "NASA MODIS True Color",
                "Live Doppler Radar",
                "NASA Thermal / Wildfire Layer",
            ],
            key="satellite_layer",
        )

        if "Doppler" in sat_layer_choice:

            st.markdown(
                "### 🌧️ Interactive Doppler Radar"
            )

            radar_tile_template = (
                get_rainviewer_radar_tile_path()
            )

            center_lat = sector_meta["lat"]
            center_lon = sector_meta["lon"]

            safe_sector = (
                selected_sector
                .replace("\\", "")
                .replace("'", "")
            )

            leaflet_html = f"""
            <!DOCTYPE html>
            <html>
            <head>

                <meta charset="utf-8">

                <link
                    rel="stylesheet"
                    href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css"
                />

                <script
                    src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js">
                </script>

                <style>

                    body {{
                        margin: 0;
                        padding: 0;
                    }}

                    #map {{
                        width: 100%;
                        height: 530px;
                        background: #0f172a;
                    }}

                </style>

            </head>

            <body>

                <div id="map"></div>

                <script>

                    var map = L.map('map').setView(
                        [{center_lat}, {center_lon}],
                        8
                    );

                    var osm = L.tileLayer(
                        'https://{{s}}.tile.openstreetmap.org/{{z}}/{{x}}/{{y}}.png',
                        {{
                            maxZoom: 19,
                            attribution: '&copy; OpenStreetMap contributors'
                        }}
                    ).addTo(map);

                    var esriSat = L.tileLayer(
                        'https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{{z}}/{{y}}/{{x}}',
                        {{
                            attribution: 'Tiles © Esri',
                            maxZoom: 18
                        }}
                    );

                    var radarLayer = L.tileLayer(
                        '{radar_tile_template}',
                        {{
                            opacity: 0.65,
                            attribution: 'Radar © RainViewer'
                        }}
                    ).addTo(map);

                    var marker = L.circleMarker(
                        [{center_lat}, {center_lon}],
                        {{
                            radius: 11,
                            fillColor: '#ef4444',
                            color: '#ffffff',
                            weight: 3,
                            fillOpacity: 0.9
                        }}
                    ).addTo(map);

                    marker.bindPopup(
                        '<b>ResQ Live Monitoring Point</b><br>'
                        + '{safe_sector}'
                    ).openPopup();

                    L.control.layers(
                        {{
                            "OpenStreetMap": osm,
                            "Satellite": esriSat
                        }},
                        {{
                            "Live Radar": radarLayer
                        }}
                    ).addTo(map);

                </script>

            </body>
            </html>
            """

            components.html(
                leaflet_html,
                height=550,
            )

        else:

            layer_id = (
                "VIIRS_SNPP_CorrectedReflectance_TrueColor"
            )

            if "MODIS" in sat_layer_choice:

                layer_id = (
                    "MODIS_Terra_CorrectedReflectance_TrueColor"
                )

            elif "Thermal" in sat_layer_choice:

                layer_id = (
                    "VIIRS_SNPP_Thermal_Anomalies_375m_All"
                )

            nasa_img, img_url, sat_source = (
                fetch_nasa_gibs_satellite_image(
                    bbox=sector_meta["bbox"],
                    layer=layer_id,
                )
            )

            if nasa_img is not None:

                st.image(
                    nasa_img,
                    caption=(
                        f"NASA Earth Observation — "
                        f"{selected_sector}"
                    ),
                    use_container_width=True,
                )

            else:

                st.warning(
                    "NASA satellite imagery is temporarily unavailable. "
                    "The rest of the monitoring dashboard remains operational."
                )

                st.caption(
                    "NASA GIBS request endpoint:"
                )

                st.code(
                    img_url,
                    language="text",
                )

        st.markdown("### 📡 Automated Observation Log")

        telemetry_df = pd.DataFrame(
            [
                {
                    "Time": "Current",
                    "Region": selected_sector,
                    "Observation": "Weather telemetry",
                    "Sensor": (
                        f"{live_telemetry['temperature']:.1f}°C / "
                        f"{live_telemetry['humidity']:.0f}% humidity"
                    ),
                    "Status": (
                        "LIVE"
                        if live_telemetry["success"]
                        else "STANDBY"
                    ),
                },
                {
                    "Time": "Recent",
                    "Region": selected_sector,
                    "Observation": "Satellite observation",
                    "Sensor": "NASA GIBS",
                    "Status": "MONITORING",
                },
                {
                    "Time": "Recent",
                    "Region": selected_sector,
                    "Observation": "Precipitation radar",
                    "Sensor": "RainViewer",
                    "Status": "MONITORING",
                },
            ]
        )

        st.dataframe(
            telemetry_df,
            use_container_width=True,
            hide_index=True,
        )

    # -------------------------------------------------------------------------
    # AI ANALYTICS TAB
    # -------------------------------------------------------------------------

    with tab_predictive:

        st.subheader(
            "🤖 Predictive Multi-Hazard Risk Analytics"
        )

        st.info(
            """
            This model is a prototype decision-support system.
            It combines environmental inputs to estimate relative hazard
            risk. It is not an official disaster forecast.
            """
        )

        sim_mode = st.radio(
            "Risk analysis input:",
            [
                "🌐 Live Telemetry",
                "🎛️ Scenario Simulation",
            ],
            horizontal=True,
            key="risk_input_mode",
        )

        input_col, score_col = st.columns(
            [1, 1]
        )

        with input_col:

            if sim_mode == "🌐 Live Telemetry":

                st.markdown(
                    "### 🌐 Live Environmental Conditions"
                )

                rainfall_val = (
                    live_telemetry["precipitation"] * 12
                )

                wind_val = (
                    live_telemetry["wind_speed"]
                )

                temp_val = (
                    live_telemetry["temperature"]
                )

                humidity_val = (
                    live_telemetry["humidity"]
                )

                river_gauge_val = (
                    sector_meta["normal_river_level"]
                    + rainfall_val * 0.05
                )

                st.metric(
                    "12-hour rainfall",
                    f"{rainfall_val:.1f} mm",
                )

                st.metric(
                    "Wind speed",
                    f"{wind_val:.1f} km/h",
                )

                st.metric(
                    "Temperature",
                    f"{temp_val:.1f} °C",
                )

                st.metric(
                    "Humidity",
                    f"{humidity_val:.1f} %",
                )

                st.metric(
                    "Model river gauge",
                    f"{river_gauge_val:.2f} m",
                )

            else:

                st.markdown(
                    "### 🎛️ Disaster Scenario Simulator"
                )

                rainfall_val = st.slider(
                    "Rainfall — 24 hours (mm)",
                    0,
                    500,
                    250,
                    5,
                    key="sim_rain",
                )

                wind_val = st.slider(
                    "Wind speed (km/h)",
                    0,
                    250,
                    115,
                    5,
                    key="sim_wind",
                )

                river_gauge_val = st.slider(
                    "River gauge increase (m)",
                    0.0,
                    15.0,
                    3.2,
                    0.1,
                    key="sim_river",
                )

                temp_val = st.slider(
                    "Temperature (°C)",
                    0,
                    50,
                    36,
                    1,
                    key="sim_temp",
                )

                humidity_val = st.slider(
                    "Humidity / soil saturation (%)",
                    0,
                    100,
                    88,
                    2,
                    key="sim_humidity",
                )

        # ---------------------------------------------------------------------
        # CALCULATE
        # ---------------------------------------------------------------------

        flood_score = min(
            100,
            max(
                0,
                int(
                    rainfall_val * 0.32
                    + river_gauge_val * 8
                    + humidity_val * 0.22
                ),
            ),
        )

        wildfire_score = min(
            100,
            max(
                0,
                int(
                    temp_val * 1.5
                    + wind_val * 0.25
                    - humidity_val * 0.45
                    - rainfall_val * 0.30
                ),
            ),
        )

        cyclone_score = min(
            100,
            max(
                0,
                int(
                    wind_val * 0.45
                    + rainfall_val * 0.22
                ),
            ),
        )

        landslide_score = min(
            100,
            max(
                0,
                int(
                    rainfall_val * 0.30
                    + humidity_val * 0.40
                ),
            ),
        )

        highest_risk = max(
            flood_score,
            wildfire_score,
            cyclone_score,
            landslide_score,
        )

        score_map = {
            flood_score: "FLOOD",
            wildfire_score: "WILDFIRE",
            cyclone_score: "CYCLONE / STORM",
            landslide_score: "LANDSLIDE",
        }

        threat_name = score_map[highest_risk]

        with score_col:

            st.markdown(
                "### 🚨 Current Risk Estimate"
            )

            a, b = st.columns(2)

            with a:
                st.metric(
                    "Flood",
                    f"{flood_score}%",
                )

                st.metric(
                    "Cyclone / Storm",
                    f"{cyclone_score}%",
                )

            with b:

                st.metric(
                    "Wildfire",
                    f"{wildfire_score}%",
                )

                st.metric(
                    "Landslide",
                    f"{landslide_score}%",
                )

            if highest_risk >= 75:

                st.markdown(
                    f"""
                    <div class="critical-banner">

                        🚨 HIGH-PRIORITY RISK DETECTED

                        <br><br>

                        {threat_name}

                        <br>

                        MODEL RISK: {highest_risk}%

                    </div>
                    """,
                    unsafe_allow_html=True,
                )

            elif highest_risk >= 50:

                st.warning(
                    f"⚠️ Elevated {threat_name} risk: "
                    f"{highest_risk}%"
                )

            else:

                st.success(
                    "✅ Current modeled conditions remain "
                    "below the high-risk threshold."
                )

            fig_gauge = go.Figure(
                go.Indicator(
                    mode="gauge+number",
                    value=highest_risk,
                    title={
                        "text": "Composite Hazard Risk"
                    },
                    gauge={
                        "axis": {
                            "range": [0, 100]
                        },
                        "bar": {
                            "color": (
                                "#dc2626"
                                if highest_risk >= 75
                                else "#f59e0b"
                                if highest_risk >= 50
                                else "#16a34a"
                            )
                        },
                        "steps": [
                            {
                                "range": [0, 50],
                                "color": "#dcfce7",
                            },
                            {
                                "range": [50, 75],
                                "color": "#fef3c7",
                            },
                            {
                                "range": [75, 100],
                                "color": "#fee2e2",
                            },
                        ],
                    },
                )
            )

            fig_gauge.update_layout(
                height=300,
                margin=dict(
                    l=20,
                    r=20,
                    t=50,
                    b=20,
                ),
            )

            st.plotly_chart(
                fig_gauge,
                use_container_width=True,
            )

        # ---------------------------------------------------------------------
        # TREND
        # ---------------------------------------------------------------------

        st.markdown("### 📈 Multi-Hazard Risk Evolution")

        timeline = [
            f"T-{48 - i * 4}h"
            for i in range(12)
        ]

        timeline += ["Current"]

        timeline += [
            f"T+{i * 4}h"
            for i in range(1, 6)
        ]

        trend_df = pd.DataFrame(
            {
                "Timeline": timeline,

                "Flood Risk": [
                    20, 22, 25, 28,
                    35, 42, 48, 55,
                    62, 70, 78, 85,
                    flood_score,
                    min(100, flood_score + 6),
                    min(100, flood_score + 10),
                    max(0, flood_score + 4),
                    max(0, flood_score - 5),
                    max(0, flood_score - 15),
                ],

                "Wildfire Risk": [
                    40, 42, 45, 48,
                    52, 50, 48, 45,
                    40, 38, 35, 30,
                    wildfire_score,
                    max(0, wildfire_score - 4),
                    max(0, wildfire_score - 8),
                    max(0, wildfire_score - 15),
                    max(0, wildfire_score - 20),
                    max(0, wildfire_score - 25),
                ],

                "Cyclone Risk": [
                    15, 15, 18, 20,
                    22, 25, 30, 40,
                    52, 65, 72, 80,
                    cyclone_score,
                    min(100, cyclone_score + 8),
                    min(100, cyclone_score + 12),
                    min(100, cyclone_score + 5),
                    max(0, cyclone_score - 10),
                    max(0, cyclone_score - 25),
                ],

                "Landslide Risk": [
                    20, 22, 25, 30,
                    34, 38, 42, 46,
                    52, 60, 68, 74,
                    landslide_score,
                    min(100, landslide_score + 5),
                    min(100, landslide_score + 9),
                    max(0, landslide_score - 3),
                    max(0, landslide_score - 10),
                    max(0, landslide_score - 18),
                ],
            }
        )

        fig_trend = px.line(
            trend_df,
            x="Timeline",
            y=[
                "Flood Risk",
                "Wildfire Risk",
                "Cyclone Risk",
                "Landslide Risk",
            ],
            markers=True,
            title="Hazard Risk Progression",
        )

        fig_trend.update_layout(
            height=400,
            legend_title="Hazard",
        )

        st.plotly_chart(
            fig_trend,
            use_container_width=True,
        )

    # -------------------------------------------------------------------------
    # BULLETINS TAB
    # -------------------------------------------------------------------------

    with tab_bulletins:

        st.subheader(
            "📢 Disaster Bulletins by Hazard"
        )

        for topic, data in (
            st.session_state.topic_bulletins.items()
        ):

            status = data["status"]

            if status == "WARNING":
                icon = "🔴"
            elif status == "WATCH":
                icon = "🟠"
            elif status == "ADVISORY":
                icon = "🟡"
            else:
                icon = "🟢"

            with st.expander(
                f"{icon} {topic} — {status} — "
                f"Updated {data['time']}",
                expanded=status in ["WARNING", "WATCH"],
            ):

                b1, b2, b3 = st.columns(
                    [2, 1, 1]
                )

                with b1:

                    st.markdown(
                        "**Situation:**"
                    )

                    st.write(
                        data["latest_update"]
                    )

                    st.caption(
                        "Source: "
                        + data["issued_by"]
                    )

                with b2:

                    st.markdown(
                        "**Telemetry:**"
                    )

                    st.write(
                        data["station_gauge"]
                    )

                    st.progress(
                        min(
                            1.0,
                            data["severity_score"] / 100
                        )
                    )

                    st.caption(
                        f"Threat score: "
                        f"{data['severity_score']}%"
                    )

                with b3:

                    st.markdown(
                        "**Recommended action:**"
                    )

                    st.info(
                        data["action_status"]
                    )

    # -------------------------------------------------------------------------
    # PREPAREDNESS TAB
    # -------------------------------------------------------------------------

    with tab_preparedness:

        st.subheader(
            "📋 Preparedness & Evacuation Hub"
        )

        checklist = st.selectbox(
            "Select hazard:",
            [
                "🌊 Flood",
                "🌪️ Cyclone",
                "🔥 Wildfire",
                "🏔️ Landslide",
                "🏚️ Earthquake",
            ],
            key="preparedness_hazard",
        )

        if "Flood" in checklist:

            items = [
                "Identify nearest elevated shelter.",
                "Store drinking water and essential supplies.",
                "Move important documents to waterproof storage.",
                "Keep emergency lighting and power banks ready.",
                "Do not enter moving floodwater.",
                "Monitor official evacuation instructions.",
            ]

        elif "Cyclone" in checklist:

            items = [
                "Secure doors, windows and loose outdoor objects.",
                "Charge phones and emergency radios.",
                "Move away from coastal and low-lying areas if ordered.",
                "Prepare drinking water and essential medicines.",
                "Do not travel during extreme winds.",
            ]

        elif "Wildfire" in checklist:

            items = [
                "Clear dry vegetation around buildings where appropriate.",
                "Keep evacuation routes accessible.",
                "Close windows if smoke conditions worsen.",
                "Prepare emergency supplies.",
                "Follow official evacuation orders.",
            ]

        elif "Landslide" in checklist:

            items = [
                "Monitor official slope and road warnings.",
                "Avoid steep slopes during prolonged rainfall.",
                "Keep roads and emergency access clear.",
                "Prepare for temporary evacuation.",
                "Report unusual ground movement to authorities.",
            ]

        else:

            items = [
                "Secure heavy furniture.",
                "Identify safe Drop, Cover and Hold locations.",
                "Keep emergency supplies available.",
                "Know multiple exit routes.",
                "After shaking stops, check for hazards.",
            ]

        for index, item in enumerate(items):

            st.checkbox(
                item,
                key=f"prep_{index}_{checklist}",
            )

        st.markdown(
            "### 🏠 Safe Shelter Planning"
        )

        shelters = pd.DataFrame(
            [
                {
                    "Shelter": "Central High-Ground Stadium",
                    "Latitude": sector_meta["lat"] + 0.02,
                    "Longitude": sector_meta["lon"] + 0.015,
                    "Capacity": "2,500",
                    "Status": "Open",
                },
                {
                    "Shelter": "District Polytechnic Relief Camp",
                    "Latitude": sector_meta["lat"] - 0.015,
                    "Longitude": sector_meta["lon"] - 0.020,
                    "Capacity": "1,200",
                    "Status": "Open",
                },
                {
                    "Shelter": "North Hill Community Center",
                    "Latitude": sector_meta["lat"] + 0.035,
                    "Longitude": sector_meta["lon"] - 0.010,
                    "Capacity": "800",
                    "Status": "Standby",
                },
                {
                    "Shelter": "Emergency Relief Base",
                    "Latitude": sector_meta["lat"] - 0.025,
                    "Longitude": sector_meta["lon"] + 0.025,
                    "Capacity": "600",
                    "Status": "Open",
                },
            ]
        )

        st.dataframe(
            shelters,
            use_container_width=True,
            hide_index=True,
        )

        fig_shelters = px.scatter_map(
            shelters,
            lat="Latitude",
            lon="Longitude",
            hover_name="Shelter",
            hover_data=[
                "Capacity",
                "Status",
            ],
            zoom=9,
            height=450,
        )

        fig_shelters.update_layout(
            map_style="open-street-map",
            margin=dict(
                l=0,
                r=0,
                t=0,
                b=0,
            ),
        )

        st.plotly_chart(
            fig_shelters,
            use_container_width=True,
        )


# =============================================================================
# DURING DISASTER
# =============================================================================

elif app_phase == "2. DURING Disaster":

    st.title(
        "🚨 DURING DISASTER — Emergency Response Center"
    )

    st.error(
        "Emergency response mode active. "
        "Always follow instructions from authorized emergency agencies."
    )

    # -------------------------------------------------------------------------
    # SOS
    # -------------------------------------------------------------------------

    st.markdown(
        """
        <div class="sos-wrapper">

            <div class="sos-title">
                🚨 EMERGENCY SOS BEACON
            </div>

            <p>
                Use this prototype control to register an emergency
                distress signal for the response queue.
            </p>

        </div>
        """,
        unsafe_allow_html=True,
    )

    with st.form("sos_form"):

        sos_col1, sos_col2 = st.columns(2)

        with sos_col1:

            sos_latitude = st.number_input(
                "Latitude",
                value=float(sector_meta["lat"]),
                format="%.6f",
            )

            sos_longitude = st.number_input(
                "Longitude",
                value=float(sector_meta["lon"]),
                format="%.6f",
            )

            people_count = st.number_input(
                "People requiring assistance",
                min_value=1,
                max_value=10000,
                value=1,
                step=1,
            )

        with sos_col2:

            triage = st.selectbox(
                "Emergency category",
                [
                    "Critical Medical Need",
                    "Trapped / Cannot Evacuate",
                    "Flood Rescue",
                    "Fire Emergency",
                    "Missing Persons",
                    "Infrastructure Emergency",
                    "Other",
                ],
            )

            details = st.text_area(
                "Situation details",
                placeholder=(
                    "Describe the situation briefly."
                ),
            )

        submit_sos = st.form_submit_button(
            "🚨 SEND SOS SIGNAL",
            type="primary",
            use_container_width=True,
        )

    if submit_sos:

        sos_id = (
            f"SOS-{datetime.now().strftime('%Y%m%d-%H%M%S')}"
        )

        st.session_state.sos_signals.insert(
            0,
            {
                "sos_id": sos_id,
                "latitude": sos_latitude,
                "longitude": sos_longitude,
                "triage": triage,
                "people_count": int(people_count),
                "details": details or "No additional details.",
                "status": "NEW",
                "timestamp": datetime.now().strftime(
                    "%H:%M:%S"
                ),
            },
        )

        st.success(
            f"SOS {sos_id} registered in the response queue."
        )

    # -------------------------------------------------------------------------
    # RESPONSE METRICS
    # -------------------------------------------------------------------------

    st.markdown("## 📊 Emergency Response Overview")

    m1, m2, m3, m4 = st.columns(4)

    with m1:
        st.metric(
            "SOS Signals",
            len(st.session_state.sos_signals),
        )

    with m2:
        st.metric(
            "Active Dispatches",
            len(st.session_state.automated_dispatches),
        )

    with m3:
        st.metric(
            "Open Warnings",
            len(st.session_state.active_early_warnings),
        )

    with m4:
        st.metric(
            "Current Status",
            st.session_state.current_hazard_status,
        )

    # -------------------------------------------------------------------------
    # SOS MAP
    # -------------------------------------------------------------------------

    st.markdown("## 📍 SOS Distress Map")

    sos_df = pd.DataFrame(
        st.session_state.sos_signals
    )

    if not sos_df.empty:

        fig_sos = px.scatter_map(
            sos_df,
            lat="latitude",
            lon="longitude",
            color="status",
            size="people_count",
            hover_name="sos_id",
            hover_data=[
                "triage",
                "people_count",
                "details",
                "timestamp",
            ],
            zoom=5,
            height=500,
        )

        fig_sos.update_layout(
            map_style="open-street-map",
            margin=dict(
                l=0,
                r=0,
                t=0,
                b=0,
            ),
        )

        st.plotly_chart(
            fig_sos,
            use_container_width=True,
        )

    # -------------------------------------------------------------------------
    # SOS QUEUE
    # -------------------------------------------------------------------------

    st.markdown("## 🚨 Emergency Response Queue")

    if not sos_df.empty:

        st.dataframe(
            sos_df[
                [
                    "sos_id",
                    "latitude",
                    "longitude",
                    "triage",
                    "people_count",
                    "details",
                    "status",
                    "timestamp",
                ]
            ],
            use_container_width=True,
            hide_index=True,
        )

    # -------------------------------------------------------------------------
    # DISPATCHES
    # -------------------------------------------------------------------------

    st.markdown("## 🚑 Automated Responder Dispatch")

    dispatch_df = pd.DataFrame(
        st.session_state.automated_dispatches
    )

    st.dataframe(
        dispatch_df,
        use_container_width=True,
        hide_index=True,
    )

    st.info(
        "Responder dispatches shown here are demonstration records. "
        "A production deployment requires authenticated integration "
        "with authorized emergency-service dispatch systems."
    )


# =============================================================================
# AFTER DISASTER
# =============================================================================

elif app_phase == "3. AFTER Disaster":

    st.title(
        "🏗️ AFTER DISASTER — Damage, Relief & Recovery"
    )

    st.markdown(
        """
        Use this workspace to register damage observations,
        track relief requirements, and monitor infrastructure recovery.
        """
    )

    # -------------------------------------------------------------------------
    # DAMAGE REPORT
    # -------------------------------------------------------------------------

    st.markdown("## 📝 Damage Reporting")

    with st.form("damage_report_form"):

        d1, d2 = st.columns(2)

        with d1:

            damage_location = st.text_input(
                "Location",
                placeholder="Example: Village / Block / Road",
            )

            damage_type = st.selectbox(
                "Damage type",
                [
                    "Road Blockage",
                    "Bridge Damage",
                    "Flooding",
                    "Building Damage",
                    "Landslide",
                    "Power Infrastructure",
                    "Water Infrastructure",
                    "Communication Infrastructure",
                    "Other",
                ],
            )

            severity = st.selectbox(
                "Severity",
                [
                    "Minor",
                    "Moderate",
                    "Severe",
                    "Critical",
                ],
            )

        with d2:

            casualties = st.number_input(
                "Reported casualties",
                min_value=0,
                max_value=100000,
                value=0,
                step=1,
            )

            supplies_needed = st.text_area(
                "Supplies / equipment required",
                placeholder=(
                    "Example: drinking water, pumps, "
                    "earthmovers, medical supplies"
                ),
            )

        submit_damage = st.form_submit_button(
            "➕ Submit Damage Report",
            use_container_width=True,
        )

    if submit_damage:

        if not damage_location.strip():

            st.warning(
                "Please provide a location."
            )

        else:

            report_id = (
                f"REP-{datetime.now().strftime('%Y%m%d-%H%M%S')}"
            )

            st.session_state.damage_reports.insert(
                0,
                {
                    "report_id": report_id,
                    "location": damage_location,
                    "damage_type": damage_type,
                    "severity": severity,
                    "casualties": int(casualties),
                    "supplies_needed": (
                        supplies_needed or "None specified"
                    ),
                    "status": "Under Assessment",
                    "timestamp": datetime.now().strftime(
                        "%Y-%m-%d %H:%M"
                    ),
                },
            )

            st.success(
                f"Damage report {report_id} submitted."
            )

    # -------------------------------------------------------------------------
    # DAMAGE TABLE
    # -------------------------------------------------------------------------

    st.markdown("## 📋 Damage Assessment Register")

    damage_df = pd.DataFrame(
        st.session_state.damage_reports
    )

    st.dataframe(
        damage_df,
        use_container_width=True,
        hide_index=True,
    )

    # -------------------------------------------------------------------------
    # RELIEF
    # -------------------------------------------------------------------------

    st.markdown("## 📦 Relief Distribution Tracking")

    relief_rows = []

    for item, values in (
        st.session_state.relief_inventory.items()
    ):

        requested = values["requested"]
        dispatched = values["dispatched"]

        remaining = max(
            0,
            requested - dispatched,
        )

        completion = (
            dispatched / requested
            if requested
            else 0
        )

        relief_rows.append(
            {
                "Resource": item,
                "Requested": requested,
                "Dispatched": dispatched,
                "Remaining": remaining,
                "Completion": completion,
            }
        )

    relief_df = pd.DataFrame(
        relief_rows
    )

    st.dataframe(
        relief_df.style.format(
            {
                "Completion": "{:.0%}"
            }
        ),
        use_container_width=True,
        hide_index=True,
    )

    fig_relief = px.bar(
        relief_df,
        x="Resource",
        y=[
            "Requested",
            "Dispatched",
        ],
        barmode="group",
        title="Relief Resource Distribution",
    )

    fig_relief.update_layout(
        height=450,
        xaxis_tickangle=-30,
    )

    st.plotly_chart(
        fig_relief,
        use_container_width=True,
    )

    # -------------------------------------------------------------------------
    # RECOVERY
    # -------------------------------------------------------------------------

    st.markdown("## 🏗️ Infrastructure Recovery")

    recovery_df = pd.DataFrame(
        [
            {
                "Infrastructure": "Road Network",
                "Status": "Assessment",
                "Recovery": 35,
            },
            {
                "Infrastructure": "Bridges",
                "Status": "Inspection",
                "Recovery": 50,
            },
            {
                "Infrastructure": "Power Supply",
                "Status": "Partial Restoration",
                "Recovery": 65,
            },
            {
                "Infrastructure": "Water Supply",
                "Status": "Emergency Repair",
                "Recovery": 45,
            },
            {
                "Infrastructure": "Telecommunications",
                "Status": "Monitoring",
                "Recovery": 75,
            },
        ]
    )

    st.dataframe(
        recovery_df,
        use_container_width=True,
        hide_index=True,
    )

    st.bar_chart(
        recovery_df.set_index(
            "Infrastructure"
        )["Recovery"]
    )


# =============================================================================
# SYSTEM SETTINGS
# =============================================================================

else:

    st.title(
        "⚙️ RESQ LIVE — System Settings"
    )

    st.markdown(
        """
        This section contains configuration and diagnostic information
        for the prototype deployment.
        """
    )

    st.markdown("## 🔌 External Feed Status")

    feed_col1, feed_col2 = st.columns(2)

    with feed_col1:

        if live_telemetry["success"]:

            st.success(
                "🟢 Open-Meteo: Connected"
            )

        else:

            st.warning(
                "🟡 Open-Meteo: Standby / unavailable"
            )

        st.info(
            "🛰️ NASA GIBS: On-demand connection"
        )

        st.info(
            "🌧️ RainViewer: On-demand connection"
        )

    with feed_col2:

        st.info(
            "🚁 UAV feed: Not connected"
        )

        st.info(
            "📡 Seismic feed: Not connected"
        )

        st.info(
            "🚑 Emergency dispatch API: Prototype mode"
        )

    st.markdown("## 🧪 Diagnostics")

    diagnostic_data = {
        "Component": [
            "Streamlit application",
            "Weather telemetry",
            "NASA satellite imagery",
            "Radar integration",
            "SOS queue",
            "Damage reporting",
            "Relief tracking",
        ],
        "Status": [
            "RUNNING",
            "CONNECTED" if live_telemetry["success"] else "STANDBY",
            "READY",
            "READY",
            "READY",
            "READY",
            "READY",
        ],
    }

    st.dataframe(
        pd.DataFrame(diagnostic_data),
        use_container_width=True,
        hide_index=True,
    )

    st.markdown("## ℹ️ Application Information")

    st.write(
        "Application: RESQ LIVE"
    )

    st.write(
        "Version: 4.0 Prototype"
    )

    st.write(
        "Deployment target: Streamlit Community Cloud"
    )

    st.write(
        "Purpose: Disaster-management decision support"
    )

    st.warning(
        "Risk scores and demonstration records are not official "
        "government warnings or emergency instructions."
    )

    if st.button(
        "🧹 Reset Demonstration Data",
        use_container_width=True,
    ):

        for key in [
            "initialized",
            "selected_sector_name",
            "current_hazard_status",
            "topic_bulletins",
            "active_early_warnings",
            "automated_dispatches",
            "sos_signals",
            "damage_reports",
            "relief_inventory",
        ]:

            st.session_state.pop(
                key,
                None,
            )

        st.success(
            "Demonstration data reset."
        )

        st.rerun()


# =============================================================================
# ACTIVE EARLY WARNINGS — GLOBAL FOOTER
# =============================================================================

st.markdown("---")

st.markdown(
    "### 📢 Active Early Warnings"
)

warning_df = pd.DataFrame(
    st.session_state.active_early_warnings
)

if not warning_df.empty:

    st.dataframe(
        warning_df,
        use_container_width=True,
        hide_index=True,
    )

else:

    st.success(
        "No active demonstration warnings."
    )


# =============================================================================
# FOOTER
# =============================================================================

st.markdown("---")

st.caption(
    "RESQ LIVE — Disaster-management decision-support prototype. "
    "Risk values are illustrative/model-based and must be verified "
    "against authoritative emergency agencies."
)
```
